---
- name: SETUP TOWER JOB TEMPLATE
  hosts: localhost
  gather_facts: false

  tasks: 

    - name: CREATE CISCO USERNAME UPDATE JOB TEMPLATE
      tower_job_template:
        name: CHANGE CISCO USER PASSWD
        job_type: "run"
        inventory: "cisco devices"
        project: "Cisco Project"
        playbook: "config.yml"
        credential: "cisco_creds"
        state: present
        survey_enabled: no
        tower_config_file: ./tower_cli.cfg